### PR TITLE
chore: add mapeo core react and state manager

### PR DESCRIPTION
**Pull request by ErikSin**
- Adds [CoMapeo-Core/React](https://github.com/digidem/comapeo-core-react)
- Adds Zustand and hook to persist state to local storage through zustand. Follows [the pattern of creating a persisted store and injecting it into React Context](https://tkdodo.eu/blog/zustand-and-react-context). This will allow for easier testing
- Adds a [RouterContext](https://tanstack.com/router/v1/docs/framework/react/guide/router-context) to the router. The context injects the device name and the persisted project id so the appropriate routing can take place. This required a rearrange of the context and providers to be outside of the RouterProvider
- Created an ActiveProjectId store. This is injected deeper into the Router after the user has created an active project. This provider guarantees a projectId saved in persisted state. Otherwise the projectId in persisted state could have been undefined. This simply takes the persisted state, and throws an error if there is no id. otherwise it just propogates to the app

**There seems to be alot of touched files, but many of them are just moving files around**

### CODE REVIEW

**Comment by ErikSin** [comment]
@cimigree the tests are broken, which ill fix tomorrow. I just dont want you to double the work into trying to integrate the new react hooks (not that you need them to for the invite work). But i just thought it would be good for you to see the structure of the hooks to inform your work.

**Review by cimigree — APPROVED** [review]
Thanks for setting this up! Looks like you were able to get rid of the hacky start to the app that you figured out yesterday.
There is one weird thing and it isn't related to this PR but maybe your previous one...
After I do npm install, I get a change in my package-lock.json
It shows this as deleted:
"@testing-library/user-event": "14.5.2",
Screenshot 2024-12-13 at 2 22 36 PM
This doesn't need to hold up this PR, but I wanted to mention it before I forget.

**Comment by ErikSin** [comment]
> Thanks for setting this up! Looks like you were able to get rid of the hacky start to the app that you figured out yesterday. There is one weird thing and it isn't related to this PR but maybe your previous one... After I do npm install, I get a change in my package-lock.json It shows this as deleted: "@testing-library/user-event": "14.5.2", Screenshot 2024-12-13 at 2 22 36 PM This doesn't need to hold up this PR, but I wanted to mention it before I forget.

oh yeah, i forgot to update my package json after i merged from main. But it should be good now

**Comment by ErikSin** [comment]
I added a bunch of things that were related but out of scope. So I decided to break up this PR into 3 smaller PRs. The code is generally the same but I just wanted to introduce things in seperate prs. Mainly because they all required a bit of configuration, and they introduced some new practices that i wanted to get more than 1 opinion on!

**Pull request closed without merging**
